# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2cf27e160b042380521d8448ca214dd0efd3b45669a74b42154ccdbeb739283e8eaea90372cc5c85f1c0f67f68d9d77131e623ddd4c96bb2c8727cec7554c23

test:
  secret_key_base: e452c175fc865a9e6587ca7de3532a7e5586d43ae1573f79a4dcd4b1f71214a61bafbe6a9f7fce1a56e074aa15e72925ad1404d34e8736b2c761525769d1dde1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
